// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lite.proto

/*
Package lite is a generated protocol buffer package.

It is generated from these files:
	lite.proto

It has these top-level messages:
	DeviceregReq
	DeviceregResp
	BaseCmd
	GateData
	CmdSetList
	CmdDef
	DevState
	DeviceList
	AudioController
	InOut
	CmdParm
	CentralController
	Power
	RecordDevice
	DevicedisconnReq
*/
package lite

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceregReq struct {
	DeviceType    string `protobuf:"bytes,1,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceRegCode string `protobuf:"bytes,2,opt,name=DeviceRegCode" json:"DeviceRegCode,omitempty"`
	DeviceId      string `protobuf:"bytes,3,opt,name=DeviceId" json:"DeviceId,omitempty"`
	MsgSeq        string `protobuf:"bytes,4,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	TempId        string `protobuf:"bytes,5,opt,name=TempId" json:"TempId,omitempty"`
}

func (m *DeviceregReq) Reset()                    { *m = DeviceregReq{} }
func (m *DeviceregReq) String() string            { return proto.CompactTextString(m) }
func (*DeviceregReq) ProtoMessage()               {}
func (*DeviceregReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceregReq) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceregReq) GetDeviceRegCode() string {
	if m != nil {
		return m.DeviceRegCode
	}
	return ""
}

func (m *DeviceregReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceregReq) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *DeviceregReq) GetTempId() string {
	if m != nil {
		return m.TempId
	}
	return ""
}

type DeviceregResp struct {
	DeviceType      string `protobuf:"bytes,1,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceId        string `protobuf:"bytes,2,opt,name=DeviceId" json:"DeviceId,omitempty"`
	BrokerAddr      string `protobuf:"bytes,3,opt,name=BrokerAddr" json:"BrokerAddr,omitempty"`
	MsgSeq          string `protobuf:"bytes,4,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	ServerPublicKey string `protobuf:"bytes,5,opt,name=ServerPublicKey" json:"ServerPublicKey,omitempty"`
	PrivateKey      string `protobuf:"bytes,6,opt,name=PrivateKey" json:"PrivateKey,omitempty"`
	Error           string `protobuf:"bytes,7,opt,name=Error" json:"Error,omitempty"`
}

func (m *DeviceregResp) Reset()                    { *m = DeviceregResp{} }
func (m *DeviceregResp) String() string            { return proto.CompactTextString(m) }
func (*DeviceregResp) ProtoMessage()               {}
func (*DeviceregResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceregResp) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceregResp) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceregResp) GetBrokerAddr() string {
	if m != nil {
		return m.BrokerAddr
	}
	return ""
}

func (m *DeviceregResp) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *DeviceregResp) GetServerPublicKey() string {
	if m != nil {
		return m.ServerPublicKey
	}
	return ""
}

func (m *DeviceregResp) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *DeviceregResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BaseCmd struct {
	DeviceType string `protobuf:"bytes,1,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceId   string `protobuf:"bytes,2,opt,name=DeviceId" json:"DeviceId,omitempty"`
	Ip         string `protobuf:"bytes,3,opt,name=Ip" json:"Ip,omitempty"`
	MsgSeq     string `protobuf:"bytes,4,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	Mark       string `protobuf:"bytes,5,opt,name=Mark" json:"Mark,omitempty"`
	Cmd        string `protobuf:"bytes,6,opt,name=Cmd" json:"Cmd,omitempty"`
	DeviceList string `protobuf:"bytes,7,opt,name=DeviceList" json:"DeviceList,omitempty"`
	Data       string `protobuf:"bytes,8,opt,name=Data" json:"Data,omitempty"`
	ServerId   string `protobuf:"bytes,9,opt,name=ServerId" json:"ServerId,omitempty"`
	UserName   string `protobuf:"bytes,10,opt,name=UserName" json:"UserName,omitempty"`
	Error      string `protobuf:"bytes,11,opt,name=Error" json:"Error,omitempty"`
	BrokerAddr string `protobuf:"bytes,12,opt,name=BrokerAddr" json:"BrokerAddr,omitempty"`
	GateId     string `protobuf:"bytes,13,opt,name=GateId" json:"GateId,omitempty"`
	Token      string `protobuf:"bytes,14,opt,name=Token" json:"Token,omitempty"`
}

func (m *BaseCmd) Reset()                    { *m = BaseCmd{} }
func (m *BaseCmd) String() string            { return proto.CompactTextString(m) }
func (*BaseCmd) ProtoMessage()               {}
func (*BaseCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BaseCmd) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *BaseCmd) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *BaseCmd) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseCmd) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *BaseCmd) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *BaseCmd) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *BaseCmd) GetDeviceList() string {
	if m != nil {
		return m.DeviceList
	}
	return ""
}

func (m *BaseCmd) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *BaseCmd) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *BaseCmd) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *BaseCmd) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BaseCmd) GetBrokerAddr() string {
	if m != nil {
		return m.BrokerAddr
	}
	return ""
}

func (m *BaseCmd) GetGateId() string {
	if m != nil {
		return m.GateId
	}
	return ""
}

func (m *BaseCmd) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GateData struct {
	GateId    string        `protobuf:"bytes,1,opt,name=GateId" json:"GateId,omitempty"`
	Name      string        `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	DefName   string        `protobuf:"bytes,3,opt,name=DefName" json:"DefName,omitempty"`
	DefKey    string        `protobuf:"bytes,4,opt,name=DefKey" json:"DefKey,omitempty"`
	DefValue  string        `protobuf:"bytes,5,opt,name=DefValue" json:"DefValue,omitempty"`
	Token     string        `protobuf:"bytes,6,opt,name=Token" json:"Token,omitempty"`
	Server    string        `protobuf:"bytes,7,opt,name=Server" json:"Server,omitempty"`
	BakServer string        `protobuf:"bytes,8,opt,name=BakServer" json:"BakServer,omitempty"`
	MsgSeq    string        `protobuf:"bytes,9,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	CmdSet    []*CmdSetList `protobuf:"bytes,10,rep,name=CmdSet" json:"CmdSet,omitempty"`
	Device    []*DeviceList `protobuf:"bytes,11,rep,name=Device" json:"Device,omitempty"`
}

func (m *GateData) Reset()                    { *m = GateData{} }
func (m *GateData) String() string            { return proto.CompactTextString(m) }
func (*GateData) ProtoMessage()               {}
func (*GateData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GateData) GetGateId() string {
	if m != nil {
		return m.GateId
	}
	return ""
}

func (m *GateData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GateData) GetDefName() string {
	if m != nil {
		return m.DefName
	}
	return ""
}

func (m *GateData) GetDefKey() string {
	if m != nil {
		return m.DefKey
	}
	return ""
}

func (m *GateData) GetDefValue() string {
	if m != nil {
		return m.DefValue
	}
	return ""
}

func (m *GateData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GateData) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *GateData) GetBakServer() string {
	if m != nil {
		return m.BakServer
	}
	return ""
}

func (m *GateData) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *GateData) GetCmdSet() []*CmdSetList {
	if m != nil {
		return m.CmdSet
	}
	return nil
}

func (m *GateData) GetDevice() []*DeviceList {
	if m != nil {
		return m.Device
	}
	return nil
}

type CmdSetList struct {
	Cmd    string        `protobuf:"bytes,1,opt,name=Cmd" json:"Cmd,omitempty"`
	Device []*DeviceList `protobuf:"bytes,2,rep,name=Device" json:"Device,omitempty"`
}

func (m *CmdSetList) Reset()                    { *m = CmdSetList{} }
func (m *CmdSetList) String() string            { return proto.CompactTextString(m) }
func (*CmdSetList) ProtoMessage()               {}
func (*CmdSetList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CmdSetList) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *CmdSetList) GetDevice() []*DeviceList {
	if m != nil {
		return m.Device
	}
	return nil
}

type CmdDef struct {
	ParmName  string `protobuf:"bytes,1,opt,name=ParmName" json:"ParmName,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	DefName   string `protobuf:"bytes,3,opt,name=DefName" json:"DefName,omitempty"`
	DefKey    string `protobuf:"bytes,4,opt,name=DefKey" json:"DefKey,omitempty"`
	DefValue  string `protobuf:"bytes,5,opt,name=DefValue" json:"DefValue,omitempty"`
	Value     string `protobuf:"bytes,6,opt,name=Value" json:"Value,omitempty"`
	EnumValue string `protobuf:"bytes,7,opt,name=EnumValue" json:"EnumValue,omitempty"`
	Range     string `protobuf:"bytes,8,opt,name=Range" json:"Range,omitempty"`
}

func (m *CmdDef) Reset()                    { *m = CmdDef{} }
func (m *CmdDef) String() string            { return proto.CompactTextString(m) }
func (*CmdDef) ProtoMessage()               {}
func (*CmdDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CmdDef) GetParmName() string {
	if m != nil {
		return m.ParmName
	}
	return ""
}

func (m *CmdDef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CmdDef) GetDefName() string {
	if m != nil {
		return m.DefName
	}
	return ""
}

func (m *CmdDef) GetDefKey() string {
	if m != nil {
		return m.DefKey
	}
	return ""
}

func (m *CmdDef) GetDefValue() string {
	if m != nil {
		return m.DefValue
	}
	return ""
}

func (m *CmdDef) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CmdDef) GetEnumValue() string {
	if m != nil {
		return m.EnumValue
	}
	return ""
}

func (m *CmdDef) GetRange() string {
	if m != nil {
		return m.Range
	}
	return ""
}

type DevState struct {
	ParmName    string `protobuf:"bytes,1,opt,name=ParmName" json:"ParmName,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	DefName     string `protobuf:"bytes,3,opt,name=DefName" json:"DefName,omitempty"`
	DefKey      string `protobuf:"bytes,4,opt,name=DefKey" json:"DefKey,omitempty"`
	DefValue    string `protobuf:"bytes,5,opt,name=DefValue" json:"DefValue,omitempty"`
	Value       string `protobuf:"bytes,6,opt,name=Value" json:"Value,omitempty"`
	DevType     string `protobuf:"bytes,7,opt,name=DevType" json:"DevType,omitempty"`
	DevIp       string `protobuf:"bytes,8,opt,name=DevIp" json:"DevIp,omitempty"`
	DevPort     string `protobuf:"bytes,9,opt,name=DevPort" json:"DevPort,omitempty"`
	DevUserName string `protobuf:"bytes,10,opt,name=DevUserName" json:"DevUserName,omitempty"`
	DevPassWord string `protobuf:"bytes,11,opt,name=DevPassWord" json:"DevPassWord,omitempty"`
}

func (m *DevState) Reset()                    { *m = DevState{} }
func (m *DevState) String() string            { return proto.CompactTextString(m) }
func (*DevState) ProtoMessage()               {}
func (*DevState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DevState) GetParmName() string {
	if m != nil {
		return m.ParmName
	}
	return ""
}

func (m *DevState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DevState) GetDefName() string {
	if m != nil {
		return m.DefName
	}
	return ""
}

func (m *DevState) GetDefKey() string {
	if m != nil {
		return m.DefKey
	}
	return ""
}

func (m *DevState) GetDefValue() string {
	if m != nil {
		return m.DefValue
	}
	return ""
}

func (m *DevState) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DevState) GetDevType() string {
	if m != nil {
		return m.DevType
	}
	return ""
}

func (m *DevState) GetDevIp() string {
	if m != nil {
		return m.DevIp
	}
	return ""
}

func (m *DevState) GetDevPort() string {
	if m != nil {
		return m.DevPort
	}
	return ""
}

func (m *DevState) GetDevUserName() string {
	if m != nil {
		return m.DevUserName
	}
	return ""
}

func (m *DevState) GetDevPassWord() string {
	if m != nil {
		return m.DevPassWord
	}
	return ""
}

type DeviceList struct {
	DeviceId    string    `protobuf:"bytes,1,opt,name=DeviceId" json:"DeviceId,omitempty"`
	Name        string    `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	UserDefName string    `protobuf:"bytes,3,opt,name=UserDefName" json:"UserDefName,omitempty"`
	DefKey      string    `protobuf:"bytes,4,opt,name=DefKey" json:"DefKey,omitempty"`
	DefValue    string    `protobuf:"bytes,5,opt,name=DefValue" json:"DefValue,omitempty"`
	Category    string    `protobuf:"bytes,6,opt,name=Category" json:"Category,omitempty"`
	Sleep       string    `protobuf:"bytes,7,opt,name=Sleep" json:"Sleep,omitempty"`
	Touch       string    `protobuf:"bytes,8,opt,name=Touch" json:"Touch,omitempty"`
	MsgSeq      string    `protobuf:"bytes,9,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	Command     *CmdDef   `protobuf:"bytes,10,opt,name=Command" json:"Command,omitempty"`
	State       *DevState `protobuf:"bytes,11,opt,name=State" json:"State,omitempty"`
}

func (m *DeviceList) Reset()                    { *m = DeviceList{} }
func (m *DeviceList) String() string            { return proto.CompactTextString(m) }
func (*DeviceList) ProtoMessage()               {}
func (*DeviceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeviceList) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceList) GetUserDefName() string {
	if m != nil {
		return m.UserDefName
	}
	return ""
}

func (m *DeviceList) GetDefKey() string {
	if m != nil {
		return m.DefKey
	}
	return ""
}

func (m *DeviceList) GetDefValue() string {
	if m != nil {
		return m.DefValue
	}
	return ""
}

func (m *DeviceList) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *DeviceList) GetSleep() string {
	if m != nil {
		return m.Sleep
	}
	return ""
}

func (m *DeviceList) GetTouch() string {
	if m != nil {
		return m.Touch
	}
	return ""
}

func (m *DeviceList) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *DeviceList) GetCommand() *CmdDef {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *DeviceList) GetState() *DevState {
	if m != nil {
		return m.State
	}
	return nil
}

type AudioController struct {
	Name    string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	DefName string `protobuf:"bytes,2,opt,name=DefName" json:"DefName,omitempty"`
	Volume  *InOut `protobuf:"bytes,3,opt,name=Volume" json:"Volume,omitempty"`
	Mute    *InOut `protobuf:"bytes,4,opt,name=Mute" json:"Mute,omitempty"`
	Level   *InOut `protobuf:"bytes,5,opt,name=Level" json:"Level,omitempty"`
}

func (m *AudioController) Reset()                    { *m = AudioController{} }
func (m *AudioController) String() string            { return proto.CompactTextString(m) }
func (*AudioController) ProtoMessage()               {}
func (*AudioController) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AudioController) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AudioController) GetDefName() string {
	if m != nil {
		return m.DefName
	}
	return ""
}

func (m *AudioController) GetVolume() *InOut {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *AudioController) GetMute() *InOut {
	if m != nil {
		return m.Mute
	}
	return nil
}

func (m *AudioController) GetLevel() *InOut {
	if m != nil {
		return m.Level
	}
	return nil
}

type InOut struct {
	Name   string     `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	OutPut []*CmdParm `protobuf:"bytes,2,rep,name=OutPut" json:"OutPut,omitempty"`
	InPut  []*CmdParm `protobuf:"bytes,3,rep,name=InPut" json:"InPut,omitempty"`
}

func (m *InOut) Reset()                    { *m = InOut{} }
func (m *InOut) String() string            { return proto.CompactTextString(m) }
func (*InOut) ProtoMessage()               {}
func (*InOut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *InOut) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InOut) GetOutPut() []*CmdParm {
	if m != nil {
		return m.OutPut
	}
	return nil
}

func (m *InOut) GetInPut() []*CmdParm {
	if m != nil {
		return m.InPut
	}
	return nil
}

type CmdParm struct {
	Name            string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	DefName         string `protobuf:"bytes,2,opt,name=DefName" json:"DefName,omitempty"`
	DefKey          string `protobuf:"bytes,3,opt,name=DefKey" json:"DefKey,omitempty"`
	DefValue        string `protobuf:"bytes,4,opt,name=DefValue" json:"DefValue,omitempty"`
	Chanel          string `protobuf:"bytes,5,opt,name=Chanel" json:"Chanel,omitempty"`
	Value           string `protobuf:"bytes,6,opt,name=Value" json:"Value,omitempty"`
	Id              string `protobuf:"bytes,7,opt,name=Id" json:"Id,omitempty"`
	DefId           string `protobuf:"bytes,8,opt,name=DefId" json:"DefId,omitempty"`
	Join            string `protobuf:"bytes,9,opt,name=Join" json:"Join,omitempty"`
	DefJoin         string `protobuf:"bytes,10,opt,name=DefJoin" json:"DefJoin,omitempty"`
	Press           string `protobuf:"bytes,11,opt,name=Press" json:"Press,omitempty"`
	Switch          string `protobuf:"bytes,12,opt,name=Switch" json:"Switch,omitempty"`
	PressSwitchMode string `protobuf:"bytes,13,opt,name=PressSwitchMode" json:"PressSwitchMode,omitempty"`
	Sort            string `protobuf:"bytes,14,opt,name=Sort" json:"Sort,omitempty"`
}

func (m *CmdParm) Reset()                    { *m = CmdParm{} }
func (m *CmdParm) String() string            { return proto.CompactTextString(m) }
func (*CmdParm) ProtoMessage()               {}
func (*CmdParm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CmdParm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CmdParm) GetDefName() string {
	if m != nil {
		return m.DefName
	}
	return ""
}

func (m *CmdParm) GetDefKey() string {
	if m != nil {
		return m.DefKey
	}
	return ""
}

func (m *CmdParm) GetDefValue() string {
	if m != nil {
		return m.DefValue
	}
	return ""
}

func (m *CmdParm) GetChanel() string {
	if m != nil {
		return m.Chanel
	}
	return ""
}

func (m *CmdParm) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CmdParm) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CmdParm) GetDefId() string {
	if m != nil {
		return m.DefId
	}
	return ""
}

func (m *CmdParm) GetJoin() string {
	if m != nil {
		return m.Join
	}
	return ""
}

func (m *CmdParm) GetDefJoin() string {
	if m != nil {
		return m.DefJoin
	}
	return ""
}

func (m *CmdParm) GetPress() string {
	if m != nil {
		return m.Press
	}
	return ""
}

func (m *CmdParm) GetSwitch() string {
	if m != nil {
		return m.Switch
	}
	return ""
}

func (m *CmdParm) GetPressSwitchMode() string {
	if m != nil {
		return m.PressSwitchMode
	}
	return ""
}

func (m *CmdParm) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type CentralController struct {
	Name    string     `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	DefName string     `protobuf:"bytes,2,opt,name=DefName" json:"DefName,omitempty"`
	Parm    []*CmdParm `protobuf:"bytes,3,rep,name=Parm" json:"Parm,omitempty"`
}

func (m *CentralController) Reset()                    { *m = CentralController{} }
func (m *CentralController) String() string            { return proto.CompactTextString(m) }
func (*CentralController) ProtoMessage()               {}
func (*CentralController) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CentralController) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CentralController) GetDefName() string {
	if m != nil {
		return m.DefName
	}
	return ""
}

func (m *CentralController) GetParm() []*CmdParm {
	if m != nil {
		return m.Parm
	}
	return nil
}

type Power struct {
	Name    string     `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	DefName string     `protobuf:"bytes,2,opt,name=DefName" json:"DefName,omitempty"`
	Parm    []*CmdParm `protobuf:"bytes,3,rep,name=Parm" json:"Parm,omitempty"`
}

func (m *Power) Reset()                    { *m = Power{} }
func (m *Power) String() string            { return proto.CompactTextString(m) }
func (*Power) ProtoMessage()               {}
func (*Power) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Power) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Power) GetDefName() string {
	if m != nil {
		return m.DefName
	}
	return ""
}

func (m *Power) GetParm() []*CmdParm {
	if m != nil {
		return m.Parm
	}
	return nil
}

type RecordDevice struct {
	Name       string     `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	DefName    string     `protobuf:"bytes,2,opt,name=DefName" json:"DefName,omitempty"`
	ChanelParm []*CmdParm `protobuf:"bytes,3,rep,name=ChanelParm" json:"ChanelParm,omitempty"`
	ActiveParm []*CmdParm `protobuf:"bytes,4,rep,name=ActiveParm" json:"ActiveParm,omitempty"`
}

func (m *RecordDevice) Reset()                    { *m = RecordDevice{} }
func (m *RecordDevice) String() string            { return proto.CompactTextString(m) }
func (*RecordDevice) ProtoMessage()               {}
func (*RecordDevice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RecordDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RecordDevice) GetDefName() string {
	if m != nil {
		return m.DefName
	}
	return ""
}

func (m *RecordDevice) GetChanelParm() []*CmdParm {
	if m != nil {
		return m.ChanelParm
	}
	return nil
}

func (m *RecordDevice) GetActiveParm() []*CmdParm {
	if m != nil {
		return m.ActiveParm
	}
	return nil
}

type DevicedisconnReq struct {
	DeviceType string `protobuf:"bytes,1,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceId   string `protobuf:"bytes,2,opt,name=DeviceId" json:"DeviceId,omitempty"`
	MsgSeq     string `protobuf:"bytes,3,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
}

func (m *DevicedisconnReq) Reset()                    { *m = DevicedisconnReq{} }
func (m *DevicedisconnReq) String() string            { return proto.CompactTextString(m) }
func (*DevicedisconnReq) ProtoMessage()               {}
func (*DevicedisconnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *DevicedisconnReq) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DevicedisconnReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DevicedisconnReq) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceregReq)(nil), "lite.DeviceregReq")
	proto.RegisterType((*DeviceregResp)(nil), "lite.DeviceregResp")
	proto.RegisterType((*BaseCmd)(nil), "lite.BaseCmd")
	proto.RegisterType((*GateData)(nil), "lite.GateData")
	proto.RegisterType((*CmdSetList)(nil), "lite.cmdSetList")
	proto.RegisterType((*CmdDef)(nil), "lite.CmdDef")
	proto.RegisterType((*DevState)(nil), "lite.DevState")
	proto.RegisterType((*DeviceList)(nil), "lite.deviceList")
	proto.RegisterType((*AudioController)(nil), "lite.AudioController")
	proto.RegisterType((*InOut)(nil), "lite.InOut")
	proto.RegisterType((*CmdParm)(nil), "lite.CmdParm")
	proto.RegisterType((*CentralController)(nil), "lite.CentralController")
	proto.RegisterType((*Power)(nil), "lite.Power")
	proto.RegisterType((*RecordDevice)(nil), "lite.RecordDevice")
	proto.RegisterType((*DevicedisconnReq)(nil), "lite.DevicedisconnReq")
}

func init() { proto.RegisterFile("lite.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 984 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x6e, 0xdb, 0xc6,
	0x13, 0x06, 0xa9, 0x7f, 0xd6, 0xc8, 0x76, 0xfc, 0x23, 0x82, 0x80, 0x08, 0x82, 0xfc, 0x1c, 0x26,
	0x2d, 0x7c, 0x69, 0x0e, 0xee, 0x13, 0xd8, 0x54, 0xd0, 0xaa, 0x8d, 0x1b, 0x81, 0x72, 0xd3, 0x5e,
	0x19, 0xed, 0x48, 0x26, 0x4c, 0x72, 0x95, 0xe5, 0x52, 0x41, 0x5e, 0xa5, 0xa7, 0x1e, 0x7b, 0xe8,
	0x23, 0xf4, 0xd0, 0x47, 0xe8, 0xb5, 0xe7, 0xbc, 0x48, 0xb1, 0x33, 0x4b, 0x91, 0x22, 0xa4, 0xa6,
	0x49, 0xd1, 0xa2, 0xb7, 0xfd, 0x66, 0x86, 0x3b, 0xdf, 0x7e, 0x33, 0xb3, 0x4b, 0x80, 0x34, 0xd1,
	0xf8, 0x74, 0xa5, 0xa4, 0x96, 0x5e, 0xd7, 0xac, 0x83, 0x1f, 0x1d, 0x38, 0x1c, 0xe3, 0x3a, 0x99,
	0xa3, 0xc2, 0x65, 0x84, 0xaf, 0xbd, 0x87, 0x00, 0x8c, 0xaf, 0xdf, 0xae, 0xd0, 0x77, 0x4e, 0x9d,
	0xb3, 0x61, 0xd4, 0xb0, 0x78, 0x4f, 0xe0, 0x88, 0x51, 0x84, 0xcb, 0x50, 0x0a, 0xf4, 0x5d, 0x0a,
	0xd9, 0x36, 0x7a, 0xf7, 0xe1, 0x80, 0x0d, 0x13, 0xe1, 0x77, 0x28, 0x60, 0x83, 0xbd, 0x7b, 0xd0,
	0xbf, 0x2a, 0x96, 0x33, 0x7c, 0xed, 0x77, 0xc9, 0x63, 0x91, 0xb1, 0x5f, 0x63, 0xb6, 0x9a, 0x08,
	0xbf, 0xc7, 0x76, 0x46, 0xc1, 0x3b, 0xa7, 0x4a, 0x49, 0x14, 0x8b, 0xd5, 0x7b, 0x39, 0x36, 0xb3,
	0xbb, 0xad, 0xec, 0x0f, 0x01, 0x2e, 0x95, 0xbc, 0x45, 0x75, 0x21, 0x84, 0xb2, 0xdc, 0x1a, 0x96,
	0xbd, 0xec, 0xce, 0xe0, 0xce, 0x0c, 0xd5, 0x1a, 0xd5, 0xb4, 0x7c, 0x95, 0x26, 0xf3, 0xaf, 0xf1,
	0xad, 0xa5, 0xd9, 0x36, 0x9b, 0x0c, 0x53, 0x95, 0xac, 0x63, 0x8d, 0x26, 0xa8, 0xcf, 0x19, 0x6a,
	0x8b, 0x77, 0x17, 0x7a, 0xcf, 0x94, 0x92, 0xca, 0x1f, 0x90, 0x8b, 0x41, 0xf0, 0xce, 0x85, 0xc1,
	0x65, 0x5c, 0x60, 0x98, 0x89, 0xbf, 0x75, 0xbe, 0x63, 0x70, 0x27, 0x2b, 0x7b, 0x2e, 0x77, 0xb2,
	0xda, 0x7b, 0x1e, 0x0f, 0xba, 0x57, 0xb1, 0xba, 0xb5, 0x87, 0xa0, 0xb5, 0x77, 0x02, 0x9d, 0x30,
	0x13, 0x96, 0x72, 0x67, 0x8b, 0xc9, 0xf3, 0xa4, 0xd0, 0x96, 0x70, 0xc3, 0x62, 0x76, 0x19, 0xc7,
	0x3a, 0xf6, 0x0f, 0x78, 0x17, 0xb3, 0x36, 0xec, 0x58, 0x92, 0x89, 0xf0, 0x87, 0xcc, 0xae, 0xc2,
	0xc6, 0xf7, 0x6d, 0x81, 0xea, 0x9b, 0x38, 0x43, 0x1f, 0xd8, 0x57, 0xe1, 0x5a, 0x97, 0x51, 0x43,
	0x97, 0x56, 0xbd, 0x0e, 0x77, 0xd5, 0xeb, 0x8b, 0x58, 0x1b, 0x25, 0x8e, 0xf8, 0x7c, 0x8c, 0xcc,
	0x6e, 0xd7, 0xf2, 0x16, 0x73, 0xff, 0x98, 0x77, 0x23, 0x10, 0xfc, 0xe2, 0xc2, 0x81, 0x09, 0x20,
	0xa2, 0xf5, 0xa7, 0xce, 0xd6, 0xa7, 0x1e, 0x74, 0x89, 0x20, 0x4b, 0x4b, 0x6b, 0xcf, 0x87, 0xc1,
	0x18, 0x17, 0x64, 0x66, 0x6d, 0x2b, 0x68, 0x76, 0x19, 0xe3, 0xc2, 0x94, 0xda, 0x0a, 0xcc, 0x88,
	0x8b, 0xb4, 0x78, 0x19, 0xa7, 0x25, 0x5a, 0x91, 0x37, 0xb8, 0x26, 0xd7, 0x6f, 0x90, 0x33, 0x3b,
	0xb1, 0x50, 0x56, 0x68, 0x8b, 0xbc, 0x07, 0x30, 0xbc, 0x8c, 0x6f, 0xad, 0x8b, 0x95, 0xae, 0x0d,
	0x8d, 0x02, 0x0f, 0x5b, 0x0d, 0xdb, 0x0f, 0x33, 0x31, 0x43, 0xed, 0xc3, 0x69, 0xe7, 0x6c, 0x74,
	0x7e, 0xf2, 0x94, 0x86, 0x7f, 0x4e, 0x36, 0x53, 0xbc, 0xc8, 0xfa, 0x4d, 0x24, 0x97, 0xd4, 0x1f,
	0x35, 0x23, 0xc5, 0xa6, 0xcc, 0x91, 0xf5, 0x07, 0x5f, 0x02, 0xd4, 0xdf, 0x57, 0xed, 0xe2, 0xd4,
	0xed, 0x52, 0xef, 0xe4, 0xbe, 0x67, 0xa7, 0xdf, 0x1c, 0xa2, 0x37, 0xc6, 0x85, 0x11, 0x6a, 0x1a,
	0xab, 0x8c, 0xb4, 0xe5, 0xbd, 0x36, 0xf8, 0xdf, 0x29, 0x05, 0x3b, 0x6c, 0x29, 0xd8, 0xfa, 0x00,
	0x86, 0xcf, 0xf2, 0x32, 0x63, 0x0f, 0x57, 0xa3, 0x36, 0x98, 0x6f, 0xa2, 0x38, 0x5f, 0xa2, 0x2d,
	0x06, 0x83, 0xe0, 0x67, 0x97, 0xc6, 0x72, 0xa6, 0x63, 0x8d, 0xff, 0xc9, 0x43, 0x51, 0x8e, 0x35,
	0xdd, 0x29, 0x83, 0x2a, 0x07, 0x41, 0x13, 0x3f, 0xc6, 0xf5, 0x64, 0x55, 0x1d, 0x88, 0x80, 0x8d,
	0x9f, 0x4a, 0xa5, 0x6d, 0x6b, 0x55, 0xd0, 0x3b, 0x85, 0xd1, 0x18, 0xd7, 0xad, 0x49, 0x6e, 0x9a,
	0x6c, 0xc4, 0x34, 0x2e, 0x8a, 0xef, 0xa4, 0x12, 0x76, 0xa4, 0x9b, 0xa6, 0xe0, 0x57, 0x17, 0xa0,
	0x6e, 0x8c, 0xad, 0x3b, 0xcd, 0x69, 0xdd, 0x69, 0xbb, 0x04, 0x3b, 0x85, 0x91, 0x49, 0xb6, 0x2d,
	0x5a, 0xd3, 0xf4, 0x51, 0xc2, 0xdd, 0x87, 0x83, 0x30, 0xd6, 0xb8, 0x94, 0xaa, 0xba, 0xb9, 0x37,
	0xd8, 0x88, 0x34, 0x4b, 0x11, 0x57, 0xd5, 0xbd, 0x4d, 0x80, 0x47, 0xb9, 0x9c, 0xdf, 0x54, 0xd2,
	0x11, 0xd8, 0x3b, 0x94, 0x9f, 0xc2, 0x20, 0x94, 0x59, 0x16, 0xe7, 0x82, 0x44, 0x1b, 0x9d, 0x1f,
	0xf2, 0x84, 0xf0, 0x28, 0x44, 0x95, 0xd3, 0x7b, 0x02, 0x3d, 0xea, 0x23, 0x12, 0x6e, 0x74, 0x7e,
	0xcc, 0x51, 0x55, 0x77, 0x45, 0xec, 0x0c, 0x7e, 0x72, 0xe0, 0xce, 0x45, 0x29, 0x12, 0x19, 0xca,
	0x5c, 0x2b, 0x99, 0xa6, 0xa8, 0x36, 0x5a, 0x39, 0xbb, 0x9b, 0xcb, 0xdd, 0x6e, 0xae, 0xc7, 0xd0,
	0x7f, 0x29, 0xd3, 0xd2, 0x0a, 0x38, 0x3a, 0x1f, 0x71, 0xa2, 0x49, 0xfe, 0xa2, 0xd4, 0x91, 0x75,
	0x79, 0xff, 0x87, 0xee, 0x55, 0xa9, 0x91, 0x64, 0x6c, 0x85, 0x90, 0xc3, 0x7b, 0x04, 0xbd, 0xe7,
	0xb8, 0xc6, 0x94, 0xe4, 0x6c, 0x45, 0xb0, 0x27, 0x58, 0x42, 0x8f, 0xf0, 0x4e, 0x7e, 0x9f, 0x40,
	0xff, 0x45, 0xa9, 0xa7, 0xa5, 0xb6, 0xd7, 0xc6, 0xd1, 0x46, 0x14, 0x33, 0x33, 0x91, 0x75, 0x7a,
	0x8f, 0xcd, 0x1e, 0x26, 0xaa, 0xb3, 0x2b, 0x8a, 0x7d, 0xc1, 0xef, 0x2e, 0x0c, 0xac, 0xe9, 0x03,
	0xb5, 0xa8, 0xfb, 0xa5, 0xb3, 0xb7, 0x5f, 0xba, 0xad, 0x7e, 0xb9, 0x07, 0xfd, 0xf0, 0x26, 0xce,
	0xed, 0xd1, 0x87, 0x91, 0x45, 0x7b, 0x06, 0xd0, 0xbc, 0xcd, 0xc2, 0xb6, 0x8f, 0xcb, 0x6f, 0xd4,
	0x18, 0x17, 0x13, 0x51, 0x8f, 0xdd, 0x82, 0xbb, 0xfd, 0x2b, 0x99, 0xe4, 0xb6, 0x73, 0x68, 0x6d,
	0x59, 0x93, 0x19, 0x36, 0xac, 0xc9, 0x73, 0x17, 0x7a, 0x53, 0x85, 0x45, 0x51, 0xbd, 0x9a, 0x04,
	0xe8, 0x29, 0x79, 0x93, 0xe8, 0xf9, 0x8d, 0x7d, 0x31, 0x2d, 0x32, 0x7f, 0x31, 0x14, 0xc0, 0xf0,
	0xca, 0xfc, 0xbf, 0xf1, 0xb3, 0xd9, 0x36, 0x1b, 0x16, 0x33, 0x33, 0xf9, 0xfc, 0x7c, 0xd2, 0x3a,
	0x10, 0xf0, 0xbf, 0x10, 0x73, 0xad, 0xe2, 0xf4, 0xa3, 0x1b, 0xee, 0x11, 0x74, 0x4d, 0x69, 0x76,
	0x97, 0x90, 0x5c, 0xc1, 0xf7, 0xd0, 0x9b, 0xca, 0x37, 0xff, 0xc4, 0xce, 0x3f, 0x38, 0x70, 0x18,
	0xe1, 0x5c, 0x2a, 0xc1, 0x57, 0xcb, 0x07, 0x66, 0xf8, 0x0c, 0x80, 0xcb, 0xbb, 0x3f, 0x4f, 0x23,
	0xc0, 0x84, 0x5f, 0xcc, 0x75, 0xb2, 0x46, 0x0a, 0xef, 0xee, 0x0c, 0xaf, 0x03, 0x82, 0x05, 0x9c,
	0x30, 0x2b, 0x91, 0x14, 0x73, 0x99, 0xe7, 0x7f, 0xe5, 0x67, 0xfc, 0xcf, 0x7e, 0x04, 0xeb, 0x2b,
	0xa8, 0xd3, 0xbc, 0x82, 0x5e, 0xf5, 0xe9, 0xf7, 0xff, 0xf3, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x27, 0x64, 0x2c, 0x1f, 0x0c, 0x0c, 0x00, 0x00,
}
