// Code generated by protoc-gen-go. DO NOT EDIT.
// source: idi.proto

/*
Package iotdevinterface is a generated protocol buffer package.

It is generated from these files:
	idi.proto

It has these top-level messages:
	DeviceregReq
	DeviceregResp
	BaseCmd
	GateData
	CmdSetList
	CmdDef
	DeviceList
	GeneralState
	DataParm
	MultimediaState
	VolumeState
	OutputState
	ChannelValue
	FarmState
	LightState
	AirConditioningState
	DevicedisconnReq
*/
package iotdevinterface

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceregReq struct {
	DeviceType    string `protobuf:"bytes,1,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceRegCode string `protobuf:"bytes,2,opt,name=DeviceRegCode" json:"DeviceRegCode,omitempty"`
	DeviceId      string `protobuf:"bytes,3,opt,name=DeviceId" json:"DeviceId,omitempty"`
	MsgSeq        string `protobuf:"bytes,4,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	TempId        string `protobuf:"bytes,5,opt,name=TempId" json:"TempId,omitempty"`
}

func (m *DeviceregReq) Reset()                    { *m = DeviceregReq{} }
func (m *DeviceregReq) String() string            { return proto.CompactTextString(m) }
func (*DeviceregReq) ProtoMessage()               {}
func (*DeviceregReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceregReq) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceregReq) GetDeviceRegCode() string {
	if m != nil {
		return m.DeviceRegCode
	}
	return ""
}

func (m *DeviceregReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceregReq) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *DeviceregReq) GetTempId() string {
	if m != nil {
		return m.TempId
	}
	return ""
}

type DeviceregResp struct {
	DeviceType      string `protobuf:"bytes,1,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceId        string `protobuf:"bytes,2,opt,name=DeviceId" json:"DeviceId,omitempty"`
	BrokerAddr      string `protobuf:"bytes,3,opt,name=BrokerAddr" json:"BrokerAddr,omitempty"`
	MsgSeq          string `protobuf:"bytes,4,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	ServerPublicKey string `protobuf:"bytes,5,opt,name=ServerPublicKey" json:"ServerPublicKey,omitempty"`
	PrivateKey      string `protobuf:"bytes,6,opt,name=PrivateKey" json:"PrivateKey,omitempty"`
	Error           string `protobuf:"bytes,7,opt,name=Error" json:"Error,omitempty"`
}

func (m *DeviceregResp) Reset()                    { *m = DeviceregResp{} }
func (m *DeviceregResp) String() string            { return proto.CompactTextString(m) }
func (*DeviceregResp) ProtoMessage()               {}
func (*DeviceregResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceregResp) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DeviceregResp) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceregResp) GetBrokerAddr() string {
	if m != nil {
		return m.BrokerAddr
	}
	return ""
}

func (m *DeviceregResp) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *DeviceregResp) GetServerPublicKey() string {
	if m != nil {
		return m.ServerPublicKey
	}
	return ""
}

func (m *DeviceregResp) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *DeviceregResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BaseCmd struct {
	DeviceType string `protobuf:"bytes,1,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceId   string `protobuf:"bytes,2,opt,name=DeviceId" json:"DeviceId,omitempty"`
	Ip         string `protobuf:"bytes,3,opt,name=Ip" json:"Ip,omitempty"`
	MsgSeq     string `protobuf:"bytes,4,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	Mark       string `protobuf:"bytes,5,opt,name=Mark" json:"Mark,omitempty"`
	Cmd        string `protobuf:"bytes,6,opt,name=Cmd" json:"Cmd,omitempty"`
	DeviceList string `protobuf:"bytes,7,opt,name=DeviceList" json:"DeviceList,omitempty"`
	Data       string `protobuf:"bytes,8,opt,name=Data" json:"Data,omitempty"`
	ServerId   string `protobuf:"bytes,9,opt,name=ServerId" json:"ServerId,omitempty"`
	UserName   string `protobuf:"bytes,10,opt,name=UserName" json:"UserName,omitempty"`
	Error      string `protobuf:"bytes,11,opt,name=Error" json:"Error,omitempty"`
	BrokerAddr string `protobuf:"bytes,12,opt,name=BrokerAddr" json:"BrokerAddr,omitempty"`
	GateId     string `protobuf:"bytes,13,opt,name=GateId" json:"GateId,omitempty"`
	Token      string `protobuf:"bytes,14,opt,name=Token" json:"Token,omitempty"`
}

func (m *BaseCmd) Reset()                    { *m = BaseCmd{} }
func (m *BaseCmd) String() string            { return proto.CompactTextString(m) }
func (*BaseCmd) ProtoMessage()               {}
func (*BaseCmd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BaseCmd) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *BaseCmd) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *BaseCmd) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BaseCmd) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *BaseCmd) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *BaseCmd) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *BaseCmd) GetDeviceList() string {
	if m != nil {
		return m.DeviceList
	}
	return ""
}

func (m *BaseCmd) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *BaseCmd) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *BaseCmd) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *BaseCmd) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BaseCmd) GetBrokerAddr() string {
	if m != nil {
		return m.BrokerAddr
	}
	return ""
}

func (m *BaseCmd) GetGateId() string {
	if m != nil {
		return m.GateId
	}
	return ""
}

func (m *BaseCmd) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GateData struct {
	GateId          string        `protobuf:"bytes,1,opt,name=GateId" json:"GateId,omitempty"`
	Name            string        `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	UserDefName     string        `protobuf:"bytes,3,opt,name=UserDefName" json:"UserDefName,omitempty"`
	UserDefGateName string        `protobuf:"bytes,4,opt,name=UserDefGateName" json:"UserDefGateName,omitempty"`
	Token           string        `protobuf:"bytes,5,opt,name=Token" json:"Token,omitempty"`
	Server          string        `protobuf:"bytes,6,opt,name=Server" json:"Server,omitempty"`
	BakServer       string        `protobuf:"bytes,7,opt,name=BakServer" json:"BakServer,omitempty"`
	MsgSeq          string        `protobuf:"bytes,8,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	CmdSet          []*CmdSetList `protobuf:"bytes,9,rep,name=CmdSet" json:"CmdSet,omitempty"`
	Device          []*DeviceList `protobuf:"bytes,10,rep,name=Device" json:"Device,omitempty"`
}

func (m *GateData) Reset()                    { *m = GateData{} }
func (m *GateData) String() string            { return proto.CompactTextString(m) }
func (*GateData) ProtoMessage()               {}
func (*GateData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GateData) GetGateId() string {
	if m != nil {
		return m.GateId
	}
	return ""
}

func (m *GateData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GateData) GetUserDefName() string {
	if m != nil {
		return m.UserDefName
	}
	return ""
}

func (m *GateData) GetUserDefGateName() string {
	if m != nil {
		return m.UserDefGateName
	}
	return ""
}

func (m *GateData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GateData) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *GateData) GetBakServer() string {
	if m != nil {
		return m.BakServer
	}
	return ""
}

func (m *GateData) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *GateData) GetCmdSet() []*CmdSetList {
	if m != nil {
		return m.CmdSet
	}
	return nil
}

func (m *GateData) GetDevice() []*DeviceList {
	if m != nil {
		return m.Device
	}
	return nil
}

type CmdSetList struct {
	Cmd    string        `protobuf:"bytes,1,opt,name=Cmd" json:"Cmd,omitempty"`
	Device []*DeviceList `protobuf:"bytes,2,rep,name=Device" json:"Device,omitempty"`
}

func (m *CmdSetList) Reset()                    { *m = CmdSetList{} }
func (m *CmdSetList) String() string            { return proto.CompactTextString(m) }
func (*CmdSetList) ProtoMessage()               {}
func (*CmdSetList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CmdSetList) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *CmdSetList) GetDevice() []*DeviceList {
	if m != nil {
		return m.Device
	}
	return nil
}

type CmdDef struct {
	ParmName    string `protobuf:"bytes,1,opt,name=ParmName" json:"ParmName,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	UserDefName string `protobuf:"bytes,3,opt,name=UserDefName" json:"UserDefName,omitempty"`
	Value       string `protobuf:"bytes,4,opt,name=Value" json:"Value,omitempty"`
	EnumValue   string `protobuf:"bytes,5,opt,name=EnumValue" json:"EnumValue,omitempty"`
	Range       string `protobuf:"bytes,6,opt,name=Range" json:"Range,omitempty"`
}

func (m *CmdDef) Reset()                    { *m = CmdDef{} }
func (m *CmdDef) String() string            { return proto.CompactTextString(m) }
func (*CmdDef) ProtoMessage()               {}
func (*CmdDef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CmdDef) GetParmName() string {
	if m != nil {
		return m.ParmName
	}
	return ""
}

func (m *CmdDef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CmdDef) GetUserDefName() string {
	if m != nil {
		return m.UserDefName
	}
	return ""
}

func (m *CmdDef) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CmdDef) GetEnumValue() string {
	if m != nil {
		return m.EnumValue
	}
	return ""
}

func (m *CmdDef) GetRange() string {
	if m != nil {
		return m.Range
	}
	return ""
}

type DeviceList struct {
	DeviceId             string                `protobuf:"bytes,1,opt,name=DeviceId" json:"DeviceId,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	UserDefName          string                `protobuf:"bytes,3,opt,name=UserDefName" json:"UserDefName,omitempty"`
	Category             string                `protobuf:"bytes,4,opt,name=Category" json:"Category,omitempty"`
	Sleep                string                `protobuf:"bytes,5,opt,name=Sleep" json:"Sleep,omitempty"`
	Touch                string                `protobuf:"bytes,6,opt,name=Touch" json:"Touch,omitempty"`
	MsgSeq               string                `protobuf:"bytes,7,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
	Command              *CmdDef               `protobuf:"bytes,8,opt,name=Command" json:"Command,omitempty"`
	GeneralState         *GeneralState         `protobuf:"bytes,9,opt,name=GeneralState" json:"GeneralState,omitempty"`
	LightState           *LightState           `protobuf:"bytes,10,opt,name=LightState" json:"LightState,omitempty"`
	AirConditioningState *AirConditioningState `protobuf:"bytes,11,opt,name=AirConditioningState" json:"AirConditioningState,omitempty"`
	FarmState            *FarmState            `protobuf:"bytes,12,opt,name=FarmState" json:"FarmState,omitempty"`
	MultimediaState      *MultimediaState      `protobuf:"bytes,13,opt,name=MultimediaState" json:"MultimediaState,omitempty"`
}

func (m *DeviceList) Reset()                    { *m = DeviceList{} }
func (m *DeviceList) String() string            { return proto.CompactTextString(m) }
func (*DeviceList) ProtoMessage()               {}
func (*DeviceList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeviceList) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceList) GetUserDefName() string {
	if m != nil {
		return m.UserDefName
	}
	return ""
}

func (m *DeviceList) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *DeviceList) GetSleep() string {
	if m != nil {
		return m.Sleep
	}
	return ""
}

func (m *DeviceList) GetTouch() string {
	if m != nil {
		return m.Touch
	}
	return ""
}

func (m *DeviceList) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func (m *DeviceList) GetCommand() *CmdDef {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *DeviceList) GetGeneralState() *GeneralState {
	if m != nil {
		return m.GeneralState
	}
	return nil
}

func (m *DeviceList) GetLightState() *LightState {
	if m != nil {
		return m.LightState
	}
	return nil
}

func (m *DeviceList) GetAirConditioningState() *AirConditioningState {
	if m != nil {
		return m.AirConditioningState
	}
	return nil
}

func (m *DeviceList) GetFarmState() *FarmState {
	if m != nil {
		return m.FarmState
	}
	return nil
}

func (m *DeviceList) GetMultimediaState() *MultimediaState {
	if m != nil {
		return m.MultimediaState
	}
	return nil
}

type GeneralState struct {
	Switch         string `protobuf:"bytes,1,opt,name=Switch" json:"Switch,omitempty"`
	Temperature    string `protobuf:"bytes,2,opt,name=Temperature" json:"Temperature,omitempty"`
	Volume         string `protobuf:"bytes,3,opt,name=Volume" json:"Volume,omitempty"`
	Poslition      string `protobuf:"bytes,4,opt,name=Poslition" json:"Poslition,omitempty"`
	O2             string `protobuf:"bytes,5,opt,name=O2" json:"O2,omitempty"`
	CO2            string `protobuf:"bytes,6,opt,name=CO2" json:"CO2,omitempty"`
	CO             string `protobuf:"bytes,7,opt,name=CO" json:"CO,omitempty"`
	WindDirection  string `protobuf:"bytes,8,opt,name=WindDirection" json:"WindDirection,omitempty"`
	Mode           string `protobuf:"bytes,9,opt,name=Mode" json:"Mode,omitempty"`
	Sensitivity    string `protobuf:"bytes,10,opt,name=Sensitivity" json:"Sensitivity,omitempty"`
	LockState      string `protobuf:"bytes,11,opt,name=LockState" json:"LockState,omitempty"`
	Beatingofheart string `protobuf:"bytes,12,opt,name=Beatingofheart" json:"Beatingofheart,omitempty"`
	Brigness       string `protobuf:"bytes,13,opt,name=Brigness" json:"Brigness,omitempty"`
}

func (m *GeneralState) Reset()                    { *m = GeneralState{} }
func (m *GeneralState) String() string            { return proto.CompactTextString(m) }
func (*GeneralState) ProtoMessage()               {}
func (*GeneralState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GeneralState) GetSwitch() string {
	if m != nil {
		return m.Switch
	}
	return ""
}

func (m *GeneralState) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *GeneralState) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *GeneralState) GetPoslition() string {
	if m != nil {
		return m.Poslition
	}
	return ""
}

func (m *GeneralState) GetO2() string {
	if m != nil {
		return m.O2
	}
	return ""
}

func (m *GeneralState) GetCO2() string {
	if m != nil {
		return m.CO2
	}
	return ""
}

func (m *GeneralState) GetCO() string {
	if m != nil {
		return m.CO
	}
	return ""
}

func (m *GeneralState) GetWindDirection() string {
	if m != nil {
		return m.WindDirection
	}
	return ""
}

func (m *GeneralState) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *GeneralState) GetSensitivity() string {
	if m != nil {
		return m.Sensitivity
	}
	return ""
}

func (m *GeneralState) GetLockState() string {
	if m != nil {
		return m.LockState
	}
	return ""
}

func (m *GeneralState) GetBeatingofheart() string {
	if m != nil {
		return m.Beatingofheart
	}
	return ""
}

func (m *GeneralState) GetBrigness() string {
	if m != nil {
		return m.Brigness
	}
	return ""
}

type DataParm struct {
	DevType     string `protobuf:"bytes,1,opt,name=DevType" json:"DevType,omitempty"`
	DevIp       string `protobuf:"bytes,2,opt,name=DevIp" json:"DevIp,omitempty"`
	DevPort     string `protobuf:"bytes,3,opt,name=DevPort" json:"DevPort,omitempty"`
	DevUsername string `protobuf:"bytes,4,opt,name=DevUsername" json:"DevUsername,omitempty"`
	DevPassword string `protobuf:"bytes,5,opt,name=DevPassword" json:"DevPassword,omitempty"`
}

func (m *DataParm) Reset()                    { *m = DataParm{} }
func (m *DataParm) String() string            { return proto.CompactTextString(m) }
func (*DataParm) ProtoMessage()               {}
func (*DataParm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DataParm) GetDevType() string {
	if m != nil {
		return m.DevType
	}
	return ""
}

func (m *DataParm) GetDevIp() string {
	if m != nil {
		return m.DevIp
	}
	return ""
}

func (m *DataParm) GetDevPort() string {
	if m != nil {
		return m.DevPort
	}
	return ""
}

func (m *DataParm) GetDevUsername() string {
	if m != nil {
		return m.DevUsername
	}
	return ""
}

func (m *DataParm) GetDevPassword() string {
	if m != nil {
		return m.DevPassword
	}
	return ""
}

type MultimediaState struct {
	Volume *VolumeState `protobuf:"bytes,1,opt,name=Volume" json:"Volume,omitempty"`
	Data   *DataParm    `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (m *MultimediaState) Reset()                    { *m = MultimediaState{} }
func (m *MultimediaState) String() string            { return proto.CompactTextString(m) }
func (*MultimediaState) ProtoMessage()               {}
func (*MultimediaState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MultimediaState) GetVolume() *VolumeState {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *MultimediaState) GetData() *DataParm {
	if m != nil {
		return m.Data
	}
	return nil
}

type VolumeState struct {
	Output *OutputState `protobuf:"bytes,1,opt,name=Output" json:"Output,omitempty"`
	Input  *OutputState `protobuf:"bytes,2,opt,name=Input" json:"Input,omitempty"`
}

func (m *VolumeState) Reset()                    { *m = VolumeState{} }
func (m *VolumeState) String() string            { return proto.CompactTextString(m) }
func (*VolumeState) ProtoMessage()               {}
func (*VolumeState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *VolumeState) GetOutput() *OutputState {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *VolumeState) GetInput() *OutputState {
	if m != nil {
		return m.Input
	}
	return nil
}

type OutputState struct {
	ChannelValue []*ChannelValue `protobuf:"bytes,1,rep,name=ChannelValue" json:"ChannelValue,omitempty"`
}

func (m *OutputState) Reset()                    { *m = OutputState{} }
func (m *OutputState) String() string            { return proto.CompactTextString(m) }
func (*OutputState) ProtoMessage()               {}
func (*OutputState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *OutputState) GetChannelValue() []*ChannelValue {
	if m != nil {
		return m.ChannelValue
	}
	return nil
}

type ChannelValue struct {
	Channel string `protobuf:"bytes,1,opt,name=Channel" json:"Channel,omitempty"`
	Value   string `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
}

func (m *ChannelValue) Reset()                    { *m = ChannelValue{} }
func (m *ChannelValue) String() string            { return proto.CompactTextString(m) }
func (*ChannelValue) ProtoMessage()               {}
func (*ChannelValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ChannelValue) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ChannelValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type FarmState struct {
	N                  string `protobuf:"bytes,1,opt,name=N" json:"N,omitempty"`
	P                  string `protobuf:"bytes,2,opt,name=P" json:"P,omitempty"`
	K                  string `protobuf:"bytes,3,opt,name=K" json:"K,omitempty"`
	O2                 string `protobuf:"bytes,4,opt,name=O2" json:"O2,omitempty"`
	CO2                string `protobuf:"bytes,5,opt,name=CO2" json:"CO2,omitempty"`
	CO                 string `protobuf:"bytes,6,opt,name=CO" json:"CO,omitempty"`
	Illumination       string `protobuf:"bytes,7,opt,name=Illumination" json:"Illumination,omitempty"`
	WindDirection      string `protobuf:"bytes,8,opt,name=WindDirection" json:"WindDirection,omitempty"`
	PH                 string `protobuf:"bytes,9,opt,name=PH" json:"PH,omitempty"`
	AirPressure        string `protobuf:"bytes,10,opt,name=AirPressure" json:"AirPressure,omitempty"`
	Flow               string `protobuf:"bytes,11,opt,name=Flow" json:"Flow,omitempty"`
	Temperature        string `protobuf:"bytes,12,opt,name=Temperature" json:"Temperature,omitempty"`
	EarmarkTemperature string `protobuf:"bytes,13,opt,name=EarmarkTemperature" json:"EarmarkTemperature,omitempty"`
	Poslition          string `protobuf:"bytes,14,opt,name=Poslition" json:"Poslition,omitempty"`
	CollarPoslition    string `protobuf:"bytes,15,opt,name=CollarPoslition" json:"CollarPoslition,omitempty"`
	ValveSwitch        string `protobuf:"bytes,16,opt,name=ValveSwitch" json:"ValveSwitch,omitempty"`
	FlowSwitch         string `protobuf:"bytes,17,opt,name=FlowSwitch" json:"FlowSwitch,omitempty"`
	WarmUpSwitch       string `protobuf:"bytes,18,opt,name=WarmUpSwitch" json:"WarmUpSwitch,omitempty"`
	ShadeTheSunSwitch  string `protobuf:"bytes,19,opt,name=ShadeTheSunSwitch" json:"ShadeTheSunSwitch,omitempty"`
	RainSwitch         string `protobuf:"bytes,20,opt,name=rainSwitch" json:"rainSwitch,omitempty"`
}

func (m *FarmState) Reset()                    { *m = FarmState{} }
func (m *FarmState) String() string            { return proto.CompactTextString(m) }
func (*FarmState) ProtoMessage()               {}
func (*FarmState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *FarmState) GetN() string {
	if m != nil {
		return m.N
	}
	return ""
}

func (m *FarmState) GetP() string {
	if m != nil {
		return m.P
	}
	return ""
}

func (m *FarmState) GetK() string {
	if m != nil {
		return m.K
	}
	return ""
}

func (m *FarmState) GetO2() string {
	if m != nil {
		return m.O2
	}
	return ""
}

func (m *FarmState) GetCO2() string {
	if m != nil {
		return m.CO2
	}
	return ""
}

func (m *FarmState) GetCO() string {
	if m != nil {
		return m.CO
	}
	return ""
}

func (m *FarmState) GetIllumination() string {
	if m != nil {
		return m.Illumination
	}
	return ""
}

func (m *FarmState) GetWindDirection() string {
	if m != nil {
		return m.WindDirection
	}
	return ""
}

func (m *FarmState) GetPH() string {
	if m != nil {
		return m.PH
	}
	return ""
}

func (m *FarmState) GetAirPressure() string {
	if m != nil {
		return m.AirPressure
	}
	return ""
}

func (m *FarmState) GetFlow() string {
	if m != nil {
		return m.Flow
	}
	return ""
}

func (m *FarmState) GetTemperature() string {
	if m != nil {
		return m.Temperature
	}
	return ""
}

func (m *FarmState) GetEarmarkTemperature() string {
	if m != nil {
		return m.EarmarkTemperature
	}
	return ""
}

func (m *FarmState) GetPoslition() string {
	if m != nil {
		return m.Poslition
	}
	return ""
}

func (m *FarmState) GetCollarPoslition() string {
	if m != nil {
		return m.CollarPoslition
	}
	return ""
}

func (m *FarmState) GetValveSwitch() string {
	if m != nil {
		return m.ValveSwitch
	}
	return ""
}

func (m *FarmState) GetFlowSwitch() string {
	if m != nil {
		return m.FlowSwitch
	}
	return ""
}

func (m *FarmState) GetWarmUpSwitch() string {
	if m != nil {
		return m.WarmUpSwitch
	}
	return ""
}

func (m *FarmState) GetShadeTheSunSwitch() string {
	if m != nil {
		return m.ShadeTheSunSwitch
	}
	return ""
}

func (m *FarmState) GetRainSwitch() string {
	if m != nil {
		return m.RainSwitch
	}
	return ""
}

type LightState struct {
	Sleep            string `protobuf:"bytes,1,opt,name=Sleep" json:"Sleep,omitempty"`
	WakeUp           string `protobuf:"bytes,2,opt,name=WakeUp" json:"WakeUp,omitempty"`
	PowerMemory      string `protobuf:"bytes,3,opt,name=PowerMemory" json:"PowerMemory,omitempty"`
	DoNotdisturb     string `protobuf:"bytes,4,opt,name=DoNotdisturb" json:"DoNotdisturb,omitempty"`
	SceneData        string `protobuf:"bytes,5,opt,name=SceneData" json:"SceneData,omitempty"`
	Switch           string `protobuf:"bytes,6,opt,name=Switch" json:"Switch,omitempty"`
	WorkMode         string `protobuf:"bytes,7,opt,name=WorkMode" json:"WorkMode,omitempty"`
	Bright           string `protobuf:"bytes,8,opt,name=Bright" json:"Bright,omitempty"`
	Temp             string `protobuf:"bytes,9,opt,name=Temp" json:"Temp,omitempty"`
	Colour           string `protobuf:"bytes,10,opt,name=Colour" json:"Colour,omitempty"`
	MicMusic         string `protobuf:"bytes,11,opt,name=MicMusic" json:"MicMusic,omitempty"`
	SwitchGradint    string `protobuf:"bytes,12,opt,name=SwitchGradint" json:"SwitchGradint,omitempty"`
	MixLightScene    string `protobuf:"bytes,13,opt,name=MixLightScene" json:"MixLightScene,omitempty"`
	MixRgbcw         string `protobuf:"bytes,14,opt,name=MixRgbcw" json:"MixRgbcw,omitempty"`
	SegmentDimming   string `protobuf:"bytes,15,opt,name=SegmentDimming" json:"SegmentDimming,omitempty"`
	SwitchNightLight string `protobuf:"bytes,16,opt,name=SwitchNightLight" json:"SwitchNightLight,omitempty"`
	CycleTiming      string `protobuf:"bytes,17,opt,name=CycleTiming" json:"CycleTiming,omitempty"`
	RandomTiming     string `protobuf:"bytes,18,opt,name=RandomTiming" json:"RandomTiming,omitempty"`
	CountDown        string `protobuf:"bytes,19,opt,name=CountDown" json:"CountDown,omitempty"`
}

func (m *LightState) Reset()                    { *m = LightState{} }
func (m *LightState) String() string            { return proto.CompactTextString(m) }
func (*LightState) ProtoMessage()               {}
func (*LightState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *LightState) GetSleep() string {
	if m != nil {
		return m.Sleep
	}
	return ""
}

func (m *LightState) GetWakeUp() string {
	if m != nil {
		return m.WakeUp
	}
	return ""
}

func (m *LightState) GetPowerMemory() string {
	if m != nil {
		return m.PowerMemory
	}
	return ""
}

func (m *LightState) GetDoNotdisturb() string {
	if m != nil {
		return m.DoNotdisturb
	}
	return ""
}

func (m *LightState) GetSceneData() string {
	if m != nil {
		return m.SceneData
	}
	return ""
}

func (m *LightState) GetSwitch() string {
	if m != nil {
		return m.Switch
	}
	return ""
}

func (m *LightState) GetWorkMode() string {
	if m != nil {
		return m.WorkMode
	}
	return ""
}

func (m *LightState) GetBright() string {
	if m != nil {
		return m.Bright
	}
	return ""
}

func (m *LightState) GetTemp() string {
	if m != nil {
		return m.Temp
	}
	return ""
}

func (m *LightState) GetColour() string {
	if m != nil {
		return m.Colour
	}
	return ""
}

func (m *LightState) GetMicMusic() string {
	if m != nil {
		return m.MicMusic
	}
	return ""
}

func (m *LightState) GetSwitchGradint() string {
	if m != nil {
		return m.SwitchGradint
	}
	return ""
}

func (m *LightState) GetMixLightScene() string {
	if m != nil {
		return m.MixLightScene
	}
	return ""
}

func (m *LightState) GetMixRgbcw() string {
	if m != nil {
		return m.MixRgbcw
	}
	return ""
}

func (m *LightState) GetSegmentDimming() string {
	if m != nil {
		return m.SegmentDimming
	}
	return ""
}

func (m *LightState) GetSwitchNightLight() string {
	if m != nil {
		return m.SwitchNightLight
	}
	return ""
}

func (m *LightState) GetCycleTiming() string {
	if m != nil {
		return m.CycleTiming
	}
	return ""
}

func (m *LightState) GetRandomTiming() string {
	if m != nil {
		return m.RandomTiming
	}
	return ""
}

func (m *LightState) GetCountDown() string {
	if m != nil {
		return m.CountDown
	}
	return ""
}

type AirConditioningState struct {
	Switch                   string `protobuf:"bytes,1,opt,name=Switch" json:"Switch,omitempty"`
	PM25                     string `protobuf:"bytes,2,opt,name=PM25" json:"PM25,omitempty"`
	AirConditioningMode      string `protobuf:"bytes,3,opt,name=AirConditioningMode" json:"AirConditioningMode,omitempty"`
	AirConditioningFlowSpeed string `protobuf:"bytes,4,opt,name=AirConditioningFlowSpeed" json:"AirConditioningFlowSpeed,omitempty"`
	FilterLife               string `protobuf:"bytes,5,opt,name=FilterLife" json:"FilterLife,omitempty"`
	Anion                    string `protobuf:"bytes,6,opt,name=Anion" json:"Anion,omitempty"`
	ChildLock                string `protobuf:"bytes,7,opt,name=ChildLock" json:"ChildLock,omitempty"`
	Light                    string `protobuf:"bytes,8,opt,name=Light" json:"Light,omitempty"`
	Uv                       string `protobuf:"bytes,9,opt,name=Uv" json:"Uv,omitempty"`
	Wet                      string `protobuf:"bytes,10,opt,name=Wet" json:"Wet,omitempty"`
	FliterReset              string `protobuf:"bytes,11,opt,name=FliterReset" json:"FliterReset,omitempty"`
	IndoorTemp               string `protobuf:"bytes,12,opt,name=IndoorTemp" json:"IndoorTemp,omitempty"`
	OutdoorTemp              string `protobuf:"bytes,13,opt,name=OutdoorTemp" json:"OutdoorTemp,omitempty"`
	IndoorHumidity           string `protobuf:"bytes,14,opt,name=IndoorHumidity" json:"IndoorHumidity,omitempty"`
	OutdoorHumidity          string `protobuf:"bytes,15,opt,name=OutdoorHumidity" json:"OutdoorHumidity,omitempty"`
	CO2                      string `protobuf:"bytes,16,opt,name=CO2" json:"CO2,omitempty"`
	Ch2OValue                string `protobuf:"bytes,17,opt,name=Ch2oValue" json:"Ch2oValue,omitempty"`
	Fault                    string `protobuf:"bytes,18,opt,name=Fault" json:"Fault,omitempty"`
}

func (m *AirConditioningState) Reset()                    { *m = AirConditioningState{} }
func (m *AirConditioningState) String() string            { return proto.CompactTextString(m) }
func (*AirConditioningState) ProtoMessage()               {}
func (*AirConditioningState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AirConditioningState) GetSwitch() string {
	if m != nil {
		return m.Switch
	}
	return ""
}

func (m *AirConditioningState) GetPM25() string {
	if m != nil {
		return m.PM25
	}
	return ""
}

func (m *AirConditioningState) GetAirConditioningMode() string {
	if m != nil {
		return m.AirConditioningMode
	}
	return ""
}

func (m *AirConditioningState) GetAirConditioningFlowSpeed() string {
	if m != nil {
		return m.AirConditioningFlowSpeed
	}
	return ""
}

func (m *AirConditioningState) GetFilterLife() string {
	if m != nil {
		return m.FilterLife
	}
	return ""
}

func (m *AirConditioningState) GetAnion() string {
	if m != nil {
		return m.Anion
	}
	return ""
}

func (m *AirConditioningState) GetChildLock() string {
	if m != nil {
		return m.ChildLock
	}
	return ""
}

func (m *AirConditioningState) GetLight() string {
	if m != nil {
		return m.Light
	}
	return ""
}

func (m *AirConditioningState) GetUv() string {
	if m != nil {
		return m.Uv
	}
	return ""
}

func (m *AirConditioningState) GetWet() string {
	if m != nil {
		return m.Wet
	}
	return ""
}

func (m *AirConditioningState) GetFliterReset() string {
	if m != nil {
		return m.FliterReset
	}
	return ""
}

func (m *AirConditioningState) GetIndoorTemp() string {
	if m != nil {
		return m.IndoorTemp
	}
	return ""
}

func (m *AirConditioningState) GetOutdoorTemp() string {
	if m != nil {
		return m.OutdoorTemp
	}
	return ""
}

func (m *AirConditioningState) GetIndoorHumidity() string {
	if m != nil {
		return m.IndoorHumidity
	}
	return ""
}

func (m *AirConditioningState) GetOutdoorHumidity() string {
	if m != nil {
		return m.OutdoorHumidity
	}
	return ""
}

func (m *AirConditioningState) GetCO2() string {
	if m != nil {
		return m.CO2
	}
	return ""
}

func (m *AirConditioningState) GetCh2OValue() string {
	if m != nil {
		return m.Ch2OValue
	}
	return ""
}

func (m *AirConditioningState) GetFault() string {
	if m != nil {
		return m.Fault
	}
	return ""
}

type DevicedisconnReq struct {
	DeviceType string `protobuf:"bytes,1,opt,name=DeviceType" json:"DeviceType,omitempty"`
	DeviceId   string `protobuf:"bytes,2,opt,name=DeviceId" json:"DeviceId,omitempty"`
	MsgSeq     string `protobuf:"bytes,3,opt,name=MsgSeq" json:"MsgSeq,omitempty"`
}

func (m *DevicedisconnReq) Reset()                    { *m = DevicedisconnReq{} }
func (m *DevicedisconnReq) String() string            { return proto.CompactTextString(m) }
func (*DevicedisconnReq) ProtoMessage()               {}
func (*DevicedisconnReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *DevicedisconnReq) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func (m *DevicedisconnReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DevicedisconnReq) GetMsgSeq() string {
	if m != nil {
		return m.MsgSeq
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceregReq)(nil), "iotdevinterface.DeviceregReq")
	proto.RegisterType((*DeviceregResp)(nil), "iotdevinterface.DeviceregResp")
	proto.RegisterType((*BaseCmd)(nil), "iotdevinterface.BaseCmd")
	proto.RegisterType((*GateData)(nil), "iotdevinterface.GateData")
	proto.RegisterType((*CmdSetList)(nil), "iotdevinterface.cmdSetList")
	proto.RegisterType((*CmdDef)(nil), "iotdevinterface.CmdDef")
	proto.RegisterType((*DeviceList)(nil), "iotdevinterface.deviceList")
	proto.RegisterType((*GeneralState)(nil), "iotdevinterface.generalState")
	proto.RegisterType((*DataParm)(nil), "iotdevinterface.dataParm")
	proto.RegisterType((*MultimediaState)(nil), "iotdevinterface.multimediaState")
	proto.RegisterType((*VolumeState)(nil), "iotdevinterface.volumeState")
	proto.RegisterType((*OutputState)(nil), "iotdevinterface.outputState")
	proto.RegisterType((*ChannelValue)(nil), "iotdevinterface.channelValue")
	proto.RegisterType((*FarmState)(nil), "iotdevinterface.farmState")
	proto.RegisterType((*LightState)(nil), "iotdevinterface.lightState")
	proto.RegisterType((*AirConditioningState)(nil), "iotdevinterface.airConditioningState")
	proto.RegisterType((*DevicedisconnReq)(nil), "iotdevinterface.DevicedisconnReq")
}

func init() { proto.RegisterFile("idi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xdd, 0x6e, 0x1b, 0xc7,
	0x15, 0xc6, 0x52, 0xd4, 0x0f, 0x87, 0xb4, 0x24, 0xaf, 0x05, 0x97, 0x55, 0x5d, 0x43, 0x58, 0xb4,
	0x85, 0x50, 0xb4, 0x42, 0x4b, 0xb7, 0x40, 0xd1, 0x00, 0x01, 0x24, 0xd2, 0xb2, 0x19, 0x8b, 0x22,
	0xb1, 0x94, 0x2c, 0xe4, 0x72, 0xc4, 0x1d, 0x91, 0x03, 0xee, 0xee, 0xd0, 0xb3, 0xb3, 0x94, 0xf5,
	0x26, 0xb9, 0xcc, 0x45, 0x1e, 0x22, 0x2f, 0x90, 0xfb, 0x20, 0xaf, 0xe0, 0xfb, 0x3c, 0x43, 0x70,
	0x66, 0xce, 0xee, 0xce, 0x2e, 0xa5, 0x44, 0x70, 0xee, 0xf6, 0x7c, 0x73, 0xe6, 0xcc, 0x99, 0x39,
	0xdf, 0xf9, 0x21, 0x49, 0x83, 0x07, 0xfc, 0x68, 0x21, 0x85, 0x12, 0xee, 0x0e, 0x17, 0x2a, 0x60,
	0x4b, 0x1e, 0x2b, 0x26, 0x6f, 0xe8, 0x84, 0x79, 0xdf, 0x3a, 0xa4, 0xd5, 0x63, 0x4b, 0x3e, 0x61,
	0x92, 0x4d, 0x7d, 0xf6, 0xc1, 0x7d, 0x49, 0x88, 0x91, 0x2f, 0xee, 0x16, 0xac, 0xed, 0x1c, 0x38,
	0x87, 0x0d, 0xdf, 0x42, 0xdc, 0xbf, 0x90, 0x27, 0x46, 0xf2, 0xd9, 0xb4, 0x2b, 0x02, 0xd6, 0xae,
	0x69, 0x95, 0x32, 0xe8, 0xee, 0x93, 0x2d, 0x03, 0xf4, 0x83, 0xf6, 0x9a, 0x56, 0xc8, 0x65, 0xf7,
	0x39, 0xd9, 0x18, 0x24, 0xd3, 0x31, 0xfb, 0xd0, 0xae, 0xeb, 0x15, 0x94, 0x00, 0xbf, 0x60, 0xd1,
	0xa2, 0x1f, 0xb4, 0xd7, 0x0d, 0x6e, 0x24, 0xef, 0x93, 0x93, 0x1d, 0xa9, 0x5d, 0x4c, 0x16, 0xbf,
	0xe9, 0xa3, 0x7d, 0x7a, 0xad, 0x72, 0xfa, 0x4b, 0x42, 0x4e, 0xa4, 0x98, 0x33, 0x79, 0x1c, 0x04,
	0x12, 0x7d, 0xb3, 0x90, 0x07, 0xbd, 0x3b, 0x24, 0x3b, 0x63, 0x26, 0x97, 0x4c, 0x8e, 0xd2, 0xeb,
	0x90, 0x4f, 0xde, 0xb1, 0x3b, 0x74, 0xb3, 0x0a, 0xc3, 0x09, 0x23, 0xc9, 0x97, 0x54, 0x31, 0x50,
	0xda, 0x30, 0x27, 0x14, 0x88, 0xbb, 0x47, 0xd6, 0x5f, 0x4b, 0x29, 0x64, 0x7b, 0x53, 0x2f, 0x19,
	0xc1, 0xfb, 0x54, 0x23, 0x9b, 0x27, 0x34, 0x61, 0xdd, 0x28, 0xf8, 0x5d, 0xf7, 0xdb, 0x26, 0xb5,
	0xfe, 0x02, 0xef, 0x55, 0xeb, 0x2f, 0x1e, 0xbc, 0x8f, 0x4b, 0xea, 0x03, 0x2a, 0xe7, 0x78, 0x09,
	0xfd, 0xed, 0xee, 0x92, 0xb5, 0x6e, 0x14, 0xa0, 0xcb, 0x6b, 0x25, 0x4f, 0xce, 0x78, 0xa2, 0xd0,
	0x61, 0x0b, 0x01, 0x2b, 0x3d, 0xaa, 0x68, 0x7b, 0xcb, 0x58, 0x81, 0x6f, 0xf0, 0xce, 0x3c, 0x49,
	0x3f, 0x68, 0x37, 0x8c, 0x77, 0x99, 0x0c, 0x6b, 0x97, 0x09, 0x93, 0xe7, 0x34, 0x62, 0x6d, 0x62,
	0xd6, 0x32, 0xb9, 0x78, 0x97, 0xa6, 0xf5, 0x2e, 0x95, 0x78, 0xb5, 0xee, 0x8b, 0xd7, 0x1b, 0xaa,
	0xe0, 0x25, 0x9e, 0x98, 0xfb, 0x19, 0x09, 0xac, 0x5d, 0x88, 0x39, 0x8b, 0xdb, 0xdb, 0xc6, 0x9a,
	0x16, 0xbc, 0x1f, 0x6b, 0x64, 0x0b, 0x14, 0xb4, 0xa3, 0xc5, 0x56, 0xa7, 0xb4, 0xd5, 0x25, 0x75,
	0xed, 0xa0, 0x79, 0x5a, 0xfd, 0xed, 0x1e, 0x90, 0x26, 0x38, 0xda, 0x63, 0x37, 0x7a, 0xc9, 0xbc,
	0xaf, 0x0d, 0x01, 0x41, 0x50, 0x04, 0x33, 0x5a, 0xcb, 0xbc, 0x78, 0x15, 0x2e, 0x5c, 0x5b, 0xb7,
	0x5c, 0x03, 0x6f, 0xcc, 0x33, 0xe1, 0xfb, 0xa3, 0xe4, 0xbe, 0x20, 0x8d, 0x13, 0x3a, 0xc7, 0x25,
	0x13, 0x81, 0x02, 0xb0, 0xc2, 0xbb, 0x55, 0x0a, 0xef, 0x2b, 0xb2, 0xd1, 0x8d, 0x82, 0x31, 0x53,
	0xed, 0xc6, 0xc1, 0xda, 0x61, 0xb3, 0xf3, 0xa7, 0xa3, 0x4a, 0xe6, 0x1f, 0x4d, 0xf4, 0x32, 0x44,
	0xd1, 0x47, 0x55, 0xd8, 0x64, 0x62, 0xdb, 0x26, 0x0f, 0x6c, 0x0a, 0xf2, 0xd0, 0xfb, 0xa8, 0xea,
	0x8d, 0x09, 0x29, 0x4c, 0x65, 0x14, 0x72, 0x0a, 0x0a, 0x15, 0x46, 0x6b, 0x8f, 0x37, 0xfa, 0x9d,
	0xa3, 0xfd, 0xef, 0xb1, 0x1b, 0xa0, 0xcc, 0x88, 0xca, 0x48, 0x3f, 0xa8, 0x31, 0x9b, 0xcb, 0x9f,
	0x19, 0xa9, 0x3d, 0xb2, 0xfe, 0x9e, 0x86, 0x69, 0x16, 0x1f, 0x23, 0xc0, 0x3b, 0xbf, 0x8e, 0xd3,
	0xc8, 0xac, 0x98, 0xc8, 0x14, 0x00, 0xec, 0xf1, 0x69, 0x3c, 0x65, 0x18, 0x1c, 0x23, 0x78, 0x3f,
	0xd5, 0x09, 0x29, 0xbc, 0x2f, 0xe5, 0xa5, 0x53, 0xc9, 0xcb, 0xcf, 0x73, 0x75, 0x9f, 0x6c, 0x75,
	0xa9, 0x62, 0x53, 0x21, 0xef, 0xd0, 0xdb, 0x5c, 0x06, 0x97, 0xc6, 0x21, 0x63, 0x8b, 0x8c, 0x46,
	0x5a, 0x30, 0xe4, 0x4a, 0x27, 0xb3, 0xcc, 0x51, 0x2d, 0x58, 0x34, 0xd9, 0x2c, 0xd1, 0xe4, 0xdf,
	0x64, 0xb3, 0x2b, 0xa2, 0x88, 0xc6, 0x81, 0xe6, 0x4f, 0xb3, 0xf3, 0x87, 0x95, 0xe8, 0x98, 0x30,
	0xf8, 0x99, 0x9e, 0x7b, 0x4c, 0x5a, 0x6f, 0x58, 0xcc, 0x24, 0x0d, 0xc7, 0x8a, 0x2a, 0xa6, 0x53,
	0xbc, 0xd9, 0xf9, 0xf3, 0xca, 0xbe, 0xa9, 0xa5, 0xe4, 0x97, 0xb6, 0xb8, 0x5f, 0x10, 0x72, 0xc6,
	0xa7, 0x33, 0x65, 0x0c, 0x10, 0x6d, 0x60, 0x95, 0x16, 0x61, 0xae, 0xe2, 0x5b, 0xea, 0xee, 0xd7,
	0x64, 0xef, 0x98, 0xcb, 0xae, 0x88, 0x03, 0xae, 0xb8, 0x88, 0x79, 0x3c, 0x35, 0x66, 0x9a, 0xda,
	0xcc, 0x5f, 0x57, 0xcc, 0xd0, 0x7b, 0x94, 0xfd, 0x7b, 0x4d, 0xb8, 0xff, 0x23, 0x8d, 0x53, 0x2a,
	0x23, 0x63, 0xaf, 0xa5, 0xed, 0xed, 0xaf, 0xd8, 0xbb, 0xc9, 0x34, 0xfc, 0x42, 0xd9, 0xfd, 0x8a,
	0xec, 0x0c, 0xd2, 0x50, 0xf1, 0x88, 0x05, 0x9c, 0x9a, 0xfd, 0x4f, 0xf4, 0xfe, 0x83, 0x95, 0xfd,
	0x51, 0x59, 0xcf, 0xaf, 0x6e, 0xf4, 0x7e, 0xae, 0x91, 0x96, 0xfd, 0x78, 0xba, 0x32, 0xdc, 0x72,
	0x35, 0x99, 0x65, 0x75, 0xca, 0x48, 0x40, 0x1f, 0x68, 0x91, 0x4c, 0x52, 0x95, 0xca, 0x8c, 0x59,
	0x36, 0x04, 0x3b, 0xdf, 0x8b, 0x30, 0xcd, 0xb9, 0x85, 0x12, 0x70, 0x7d, 0x24, 0x92, 0x50, 0xdf,
	0x1e, 0x79, 0x55, 0x00, 0xd0, 0x42, 0x86, 0x1d, 0x64, 0x55, 0x6d, 0xd8, 0xd1, 0x39, 0x3d, 0xec,
	0xe4, 0x6d, 0x61, 0xd8, 0x01, 0x8d, 0xee, 0x10, 0xa9, 0x54, 0xeb, 0x0e, 0x61, 0x28, 0xb8, 0xe2,
	0x71, 0xd0, 0xe3, 0x92, 0x4d, 0xb4, 0x4d, 0x53, 0x8c, 0xca, 0xa0, 0x6e, 0x39, 0x30, 0x31, 0x34,
	0xb0, 0xe5, 0xc0, 0xa0, 0x70, 0x40, 0x9a, 0x63, 0x16, 0x27, 0x5c, 0xf1, 0x25, 0x57, 0x77, 0xd8,
	0x13, 0x6c, 0x08, 0x7c, 0x3d, 0x13, 0x93, 0x79, 0x11, 0xe4, 0x86, 0x5f, 0x00, 0xee, 0xdf, 0xc8,
	0xf6, 0x09, 0xa3, 0x8a, 0xc7, 0x53, 0x71, 0x33, 0x63, 0x54, 0x2a, 0x6c, 0x11, 0x15, 0x14, 0x12,
	0xe9, 0x44, 0xf2, 0x69, 0xcc, 0x92, 0x04, 0x1b, 0x45, 0x2e, 0x7b, 0xdf, 0x38, 0x64, 0x2b, 0xa0,
	0x8a, 0x42, 0x59, 0x71, 0xdb, 0x64, 0xb3, 0xc7, 0x96, 0x56, 0xe3, 0xcd, 0x44, 0xc8, 0xac, 0x1e,
	0x5b, 0xf6, 0x17, 0xf8, 0xd0, 0x46, 0x40, 0xfd, 0x91, 0x90, 0x0a, 0xdf, 0x38, 0x13, 0xe1, 0x6a,
	0x3d, 0xb6, 0x84, 0x6c, 0x8e, 0x8b, 0x66, 0x60, 0x43, 0xa8, 0x31, 0xa2, 0x49, 0x72, 0x2b, 0x64,
	0x36, 0xf6, 0xd8, 0x90, 0xb7, 0x24, 0x3b, 0x15, 0xbe, 0xb8, 0xff, 0xc9, 0x63, 0xea, 0x68, 0x86,
	0xbd, 0x58, 0x61, 0xd8, 0x52, 0x2f, 0x1b, 0x76, 0x65, 0x11, 0xff, 0x27, 0x36, 0xea, 0x9a, 0xde,
	0xf3, 0xc7, 0xd5, 0x1a, 0x8c, 0xf7, 0x37, 0x3d, 0xdc, 0xbb, 0x25, 0x4d, 0xcb, 0x0a, 0x9c, 0x39,
	0x4c, 0xd5, 0x22, 0x55, 0x0f, 0x9e, 0x29, 0xf4, 0x32, 0x9e, 0x69, 0x74, 0xdd, 0x0e, 0x59, 0xef,
	0xc7, 0xb0, 0xa9, 0xf6, 0x88, 0x4d, 0x46, 0xd5, 0x1b, 0x91, 0xa6, 0x85, 0x42, 0xb1, 0xe9, 0xce,
	0x68, 0x1c, 0xb3, 0xd0, 0xd4, 0x65, 0x47, 0xb7, 0x90, 0xd5, 0x62, 0x33, 0xb1, 0x94, 0xfc, 0xd2,
	0x16, 0xef, 0x4b, 0xd2, 0xb2, 0x57, 0x21, 0x60, 0xb8, 0x9e, 0x05, 0x18, 0xc5, 0xa2, 0x2f, 0xd4,
	0xac, 0xbe, 0xe0, 0xfd, 0x50, 0x27, 0x8d, 0x3c, 0xe7, 0xdd, 0x16, 0x71, 0xce, 0x71, 0x9f, 0x73,
	0x0e, 0xd2, 0x08, 0xb5, 0x9d, 0x11, 0x48, 0xef, 0x90, 0x04, 0xce, 0x3b, 0xcc, 0xa2, 0x7a, 0x35,
	0x8b, 0xd6, 0xab, 0x59, 0xb4, 0x91, 0x67, 0x91, 0x47, 0x5a, 0xfd, 0x30, 0x4c, 0x23, 0x1e, 0x53,
	0x9d, 0x44, 0x26, 0xbf, 0x4a, 0xd8, 0x23, 0x33, 0x6d, 0x9b, 0xd4, 0x46, 0x6f, 0x31, 0xcf, 0x6a,
	0xa3, 0xb7, 0x40, 0xb4, 0x63, 0x2e, 0x47, 0x92, 0x25, 0x09, 0x54, 0x0a, 0xcc, 0x32, 0x0b, 0x82,
	0xdc, 0x3c, 0x0d, 0xc5, 0x2d, 0x26, 0x98, 0xfe, 0xae, 0xd6, 0x97, 0xd6, 0x6a, 0x7d, 0x39, 0x22,
	0xee, 0x6b, 0x2a, 0x23, 0x2a, 0xe7, 0xb6, 0xa2, 0xc9, 0xaf, 0x7b, 0x56, 0xca, 0x75, 0x67, 0xbb,
	0x5a, 0x77, 0x0e, 0xc9, 0x4e, 0x57, 0x84, 0x21, 0x95, 0x85, 0xce, 0x8e, 0x99, 0xa0, 0x2a, 0x30,
	0x78, 0xf6, 0x9e, 0x86, 0x4b, 0x86, 0x65, 0x71, 0xd7, 0x78, 0x66, 0x41, 0x30, 0x36, 0xc2, 0x1d,
	0x50, 0xe1, 0xa9, 0x19, 0x1b, 0x0b, 0x04, 0xde, 0xfa, 0x8a, 0xca, 0xe8, 0x72, 0x81, 0x1a, 0xae,
	0x79, 0x6b, 0x1b, 0x73, 0xff, 0x41, 0x9e, 0x8e, 0x67, 0x34, 0x60, 0x17, 0x33, 0x36, 0x4e, 0x63,
	0x54, 0x7c, 0xa6, 0x15, 0x57, 0x17, 0xe0, 0x44, 0x49, 0x79, 0xa6, 0xb6, 0x67, 0x4e, 0x2c, 0x10,
	0x3d, 0x2b, 0x14, 0x2d, 0xad, 0xe8, 0xde, 0x8e, 0xdd, 0xbd, 0x9f, 0x93, 0x8d, 0x2b, 0x3a, 0x67,
	0x97, 0x59, 0x91, 0x41, 0x09, 0x2e, 0x3c, 0x12, 0xb7, 0x4c, 0x0e, 0x58, 0x04, 0xa3, 0x00, 0x4e,
	0x0a, 0x16, 0x04, 0x17, 0xea, 0x89, 0x73, 0xa1, 0x02, 0x9e, 0xa8, 0x54, 0x5e, 0x23, 0xf1, 0x4a,
	0x18, 0x3c, 0xff, 0x78, 0xc2, 0x62, 0x3d, 0xfd, 0x66, 0x23, 0x4e, 0x0e, 0x58, 0x6d, 0x66, 0xa3,
	0xd4, 0x66, 0xf6, 0xc9, 0xd6, 0x95, 0x90, 0x73, 0x5d, 0xba, 0x0d, 0x25, 0x73, 0x19, 0xf6, 0x40,
	0x19, 0x9d, 0xa9, 0x6c, 0xfc, 0x34, 0x12, 0xd0, 0x09, 0xe2, 0x9e, 0x95, 0x7a, 0xf8, 0x06, 0xdd,
	0xae, 0x08, 0x45, 0x2a, 0x91, 0x7f, 0x28, 0x81, 0xfd, 0x01, 0x9f, 0x0c, 0xd2, 0x84, 0x4f, 0x90,
	0x7e, 0xb9, 0x0c, 0x74, 0x37, 0x5e, 0xbc, 0x91, 0x34, 0xe0, 0x71, 0x56, 0xdd, 0xcb, 0x20, 0x68,
	0x0d, 0xf8, 0x47, 0x33, 0x23, 0xc0, 0x75, 0x90, 0x81, 0x65, 0xd0, 0x9c, 0xf3, 0xd1, 0x9f, 0x5e,
	0x4f, 0x6e, 0x91, 0x7b, 0xb9, 0x0c, 0x6d, 0x64, 0xcc, 0xa6, 0x11, 0x8b, 0x55, 0x8f, 0x47, 0x11,
	0x8f, 0xa7, 0xc8, 0xbc, 0x0a, 0xea, 0xfe, 0x9d, 0xec, 0x9a, 0xa3, 0xcf, 0xc1, 0xae, 0x36, 0x8e,
	0xec, 0x5b, 0xc1, 0x21, 0x66, 0xdd, 0xbb, 0x49, 0xc8, 0x2e, 0xb8, 0x36, 0x68, 0x38, 0x68, 0x43,
	0x10, 0x33, 0x9f, 0xc6, 0x81, 0x88, 0x50, 0x05, 0x49, 0x68, 0x63, 0x10, 0xb3, 0xae, 0x48, 0x63,
	0xd5, 0x13, 0xb7, 0x31, 0x92, 0xaf, 0x00, 0xbc, 0xef, 0xeb, 0x64, 0xef, 0xbe, 0x01, 0xe7, 0xc1,
	0x99, 0xc1, 0x25, 0xf5, 0xd1, 0xa0, 0xf3, 0xdf, 0x6c, 0x0c, 0x85, 0x6f, 0xf7, 0x5f, 0xe4, 0x59,
	0x65, 0x1c, 0xd2, 0xb1, 0x36, 0x24, 0xbb, 0x6f, 0xc9, 0xfd, 0x3f, 0x69, 0x57, 0x60, 0x9d, 0x5a,
	0x0b, 0xc6, 0x02, 0x24, 0xde, 0x83, 0xeb, 0x3a, 0x33, 0x79, 0xa8, 0x98, 0x3c, 0xe3, 0x37, 0xd9,
	0xa0, 0x6d, 0x21, 0x90, 0x18, 0xc7, 0x31, 0xe4, 0x3e, 0x0e, 0xb0, 0x5a, 0xd0, 0xcf, 0x30, 0xe3,
	0x61, 0x00, 0x9d, 0x3f, 0xfb, 0x15, 0x94, 0x03, 0xb0, 0xe7, 0xcc, 0x62, 0xa1, 0x11, 0xa0, 0x0a,
	0x5e, 0x2e, 0xb3, 0x2a, 0x78, 0xb9, 0x84, 0x0a, 0x7c, 0xc5, 0x14, 0xb2, 0x0f, 0x3e, 0x21, 0x44,
	0xa7, 0x21, 0x57, 0x4c, 0xfa, 0x2c, 0x61, 0x0a, 0xd9, 0x67, 0x43, 0xe0, 0x6d, 0x3f, 0x0e, 0x84,
	0x90, 0x9a, 0xce, 0xf8, 0xf3, 0xb3, 0x40, 0xc0, 0xc2, 0x30, 0x55, 0xb9, 0x82, 0x21, 0x9e, 0x0d,
	0x01, 0xb5, 0x8c, 0xfe, 0xdb, 0x34, 0xe2, 0x01, 0x0c, 0x39, 0x86, 0x7c, 0x15, 0x14, 0xaa, 0x1f,
	0x6e, 0xcb, 0x15, 0xb1, 0xfa, 0x55, 0xe0, 0xac, 0x93, 0xec, 0x16, 0x9d, 0x44, 0xbf, 0x4e, 0x47,
	0x98, 0xee, 0xf5, 0x34, 0x7b, 0x1d, 0x04, 0xe0, 0x75, 0x4e, 0x69, 0x1a, 0x2a, 0xe4, 0x97, 0x11,
	0xbc, 0x1b, 0xb2, 0x6b, 0x7e, 0x9c, 0x04, 0x3c, 0x99, 0x88, 0x38, 0x7e, 0xcc, 0x9f, 0x3f, 0xbf,
	0xf6, 0xc7, 0x43, 0xf1, 0x13, 0x63, 0xcd, 0xfe, 0x89, 0x71, 0xbd, 0xa1, 0xff, 0x79, 0x7a, 0xf5,
	0x4b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x56, 0xb8, 0x02, 0x3b, 0x86, 0x12, 0x00, 0x00,
}
